version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test123
      - MONGO_INITDB_DATABASE=chatify

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    links:
      - redis

    ports:
      - 3000:3000